
LOAD DATA
TRUNCATE
INTO TABLE WDI_foot_note
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"' 
TRAILING NULLCOLS
(  
CountryCode CHAR ,
SeriesCode CHAR ,
Year CHAR ,
DESCRIPTION CHAR
)
